<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>PuimesAddin</RootNamespace>
    <AssemblyName>PuimesAddin</AssemblyName>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <StartAction>Program</StartAction>
    <StartProgram>C:\Program Files (x86)\ABB\RobotStudio 2026\Bin\RobotStudio.exe</StartProgram>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <StartAction>Program</StartAction>
    <StartProgram>C:\Program Files (x86)\ABB\RobotStudio 2026\Bin\RobotStudio.exe</StartProgram>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ABB.Robotics.Controllers.PC">
      <HintPath>C:\Program Files (x86)\ABB\SDK\RobotStudio 2026 SDK\ABB.Robotics.Controllers.PC.dll</HintPath>
    </Reference>
    <Reference Include="ABB.Robotics.Math">
      <HintPath>C:\Program Files (x86)\ABB\SDK\RobotStudio 2026 SDK\ABB.Robotics.Math.dll</HintPath>
    </Reference>
    <Reference Include="ABB.Robotics.RobotStudio">
      <HintPath>C:\Program Files (x86)\ABB\SDK\RobotStudio 2026 SDK\ABB.Robotics.RobotStudio.dll</HintPath>
    </Reference>
    <Reference Include="ABB.Robotics.RobotStudio.Controllers">
      <HintPath>C:\Program Files (x86)\ABB\SDK\RobotStudio 2026 SDK\ABB.Robotics.RobotStudio.Controllers.dll</HintPath>
    </Reference>
    <Reference Include="ABB.Robotics.RobotStudio.Documents">
      <HintPath>C:\Program Files (x86)\ABB\SDK\RobotStudio 2026 SDK\ABB.Robotics.RobotStudio.Documents.dll</HintPath>
    </Reference>
    <Reference Include="ABB.Robotics.RobotStudio.Environment">
      <HintPath>C:\Program Files (x86)\ABB\SDK\RobotStudio 2026 SDK\ABB.Robotics.RobotStudio.Environment.dll</HintPath>
    </Reference>
    <Reference Include="ABB.Robotics.RobotStudio.Stations">
      <HintPath>C:\Program Files (x86)\ABB\SDK\RobotStudio 2026 SDK\ABB.Robotics.RobotStudio.Stations.dll</HintPath>
    </Reference>
    <Reference Include="ABB.Robotics.RobotStudio.Stations.Forms">
      <HintPath>C:\Program Files (x86)\ABB\SDK\RobotStudio 2026 SDK\ABB.Robotics.RobotStudio.Stations.Forms.dll</HintPath>
    </Reference>
    <Reference Include="ABB.Robotics.RobotStudio.UI">
      <HintPath>C:\Program Files (x86)\ABB\SDK\RobotStudio 2026 SDK\ABB.Robotics.RobotStudio.UI.dll</HintPath>
    </Reference>
    <Reference Include="RobotStudio.Resources">
      <HintPath>C:\Program Files (x86)\ABB\SDK\RobotStudio 2026 SDK\RobotStudio.Resources.dll</HintPath>
    </Reference>
    </ItemGroup>
  <ItemGroup>
    <Compile Include="Array.cs" />
    <Compile Include="AutoMoveParam.cs" />
    <Compile Include="BasePlate_constructor.cs" />
    <Compile Include="CADExport.cs" />
    <Compile Include="Create_BasePlate.cs" />
    <Compile Include="frmCreateAluminiumProfile.cs" />
    <Compile Include="frmCreateAluminiumProfile.Designer.cs">
      <DependentUpon>frmCreateAluminiumProfile.cs</DependentUpon>
    </Compile>
    <Compile Include="frmCreateTextBuilder.cs" />
    <Compile Include="frmAutoMarkUpBuilder.cs" />
    <Compile Include="frmAutoMoveParam.cs" />
    <Compile Include="frmAutoMoveParam.Designer.cs">
      <DependentUpon>frmAutoMoveParam.cs</DependentUpon>
    </Compile>
    <Compile Include="frmCreateBoxBuilder.cs" />
    <Compile Include="frmMainWindowSize.cs" />
    <Compile Include="frmZoom.cs" />
    <Compile Include="frmZoom.Designer.cs">
      <DependentUpon>frmZoom.cs</DependentUpon>
    </Compile>
    <Compile Include="Hide_CS.cs" />
    <Compile Include="Copy_Position.cs" />
    <Compile Include="main.cs" />
    <Compile Include="Make_Floor.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="Create_Raiser.cs" />
    <Compile Include="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Include="Raiser_constructor.cs" />
    <Compile Include="JoinParts.cs" />
    <Compile Include="RenameMoveTargets.cs" />
    <Compile Include="TextCreator.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
    <None Include="Puime_s_Addin.rsaddin">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="frmAutoMarkUpBuilder.resx" />
    <EmbeddedResource Include="frmAutoMoveParam.resx">
      <DependentUpon>frmAutoMoveParam.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="frmCreateAluminiumProfile.resx">
      <DependentUpon>frmCreateAluminiumProfile.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="frmCreateBoxBuilder.resx" />
    <EmbeddedResource Include="frmZoom.resx">
      <DependentUpon>frmZoom.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\BT_floor.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\BT_paste.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\BT_raiser.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\BT_box_65.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\BigMetNut.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Grommet.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Klammer.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Metnut.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Nut.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Panzer.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\PlasticNut.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\RetClip.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\SClip.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\SmallSnapClip.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Snap.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\TrimClipPlastic.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\TrimFastener.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\BT_marks.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\BT_baseplate.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Image1.bmp" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\BT_rename.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\BT_joinparts.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\PA.png" />
    <None Include="Resources\more.png" />
    <None Include="Resources\less.png" />
    <None Include="Resources\menos.png" />
    <None Include="Resources\mas.png" />
    <None Include="Resources\BT_cadexport.png" />
    <None Include="Resources\Alum_Prof_100_65.png" />
    <None Include="Resources\Alum_Prof_80_65.png" />
    <None Include="Resources\Alum_Prof_90_65.png" />
    <None Include="Resources\Alum_Prof_60_65.png" />
    <None Include="Resources\Alum_Prof_40_65.png" />
    <None Include="Resources\Alum_Prof_50_65.png" />
    <None Include="Resources\Alum_Prof_30_65.png" />
    <None Include="Resources\Alum_Prof_20_65.png" />
    <None Include="Resources\Alum_Prof_20_65_b.png" />
    <None Include="Resources\BT_move.png" />
    <None Include="Resources\BT_move2.png" />
    <None Include="Resources\BT_camera.png" />
    <Content Include="Resources\BT_textcreator.png" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="C:\Program Files %28x86%29\ABB\SDK\RobotStudio 2024 SDK\ABB.Robotics.Controllers.PC.dll" />
    <Analyzer Include="C:\Program Files %28x86%29\ABB\SDK\RobotStudio 2024 SDK\ABB.Robotics.Math.dll" />
    <Analyzer Include="C:\Program Files %28x86%29\ABB\SDK\RobotStudio 2024 SDK\ABB.Robotics.RobotStudio.Controllers.dll" />
    <Analyzer Include="C:\Program Files %28x86%29\ABB\SDK\RobotStudio 2024 SDK\ABB.Robotics.RobotStudio.dll" />
    <Analyzer Include="C:\Program Files %28x86%29\ABB\SDK\RobotStudio 2024 SDK\ABB.Robotics.RobotStudio.Documents.dll" />
    <Analyzer Include="C:\Program Files %28x86%29\ABB\SDK\RobotStudio 2024 SDK\ABB.Robotics.RobotStudio.Environment.dll" />
    <Analyzer Include="C:\Program Files %28x86%29\ABB\SDK\RobotStudio 2024 SDK\ABB.Robotics.RobotStudio.Stations.dll" />
    <Analyzer Include="C:\Program Files %28x86%29\ABB\SDK\RobotStudio 2024 SDK\ABB.Robotics.RobotStudio.Stations.Forms.dll" />
    <Analyzer Include="C:\Program Files %28x86%29\ABB\SDK\RobotStudio 2024 SDK\ABB.Robotics.RobotStudio.UI.dll" />
    <Analyzer Include="C:\Program Files %28x86%29\ABB\SDK\RobotStudio 2024 SDK\RobotStudio.Resources.dll" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /y &quot;$(TargetPath)&quot; &quot;C:\Users\esu01142\AppData\Local\ABB\DistributionPackages2\PuimesAddin-2026.0\RobotStudio\Add-In\&quot;" />
  </Target>
</Project>